//
//  DataMocker.swift
//  SofaScoreAcademy
//
//  Created by Matija Kruljac on 24.03.2021..
//

import Foundation

struct DataMocker {
    
    var players: [Player] {
        [Player(id: 0,
                image: "messi",
                name: "Lionel Messi",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 180,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 1,
                image: "ronaldo",
                name: "Cristiano Ronaldo",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 190,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 2,
                image: "ibrahimovic",
                name: "Zlatan Ibrahimovic",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 175,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 3,
                image: "messi",
                name: "Lionel Messi",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 195,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 4,
                image: "ronaldo",
                name: "Cristiano Ronaldo",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 160,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 5,
                image: "ibrahimovic",
                name: "Zlatan Ibrahimovic",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 185,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 6,
                image: "messi",
                name: "Lionel Messi",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 185,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 7,
                image: "ronaldo",
                name: "Cristiano Ronaldo",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 183,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 8,
                image: "ibrahimovic",
                name: "Zlatan Ibrahimovic",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 169,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 9,
                image: "messi",
                name: "Lionel Messi",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 179,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 10,
                image: "ronaldo",
                name: "Cristiano Ronaldo",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 197,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5),
         Player(id: 11,
                image: "ibrahimovic",
                name: "Zlatan Ibrahimovic",
                nationality: "CRO",
                dateOfBirth: "23.4.1234.",
                height: 181,
                preferredFoot: "Left",
                position: "C",
                shirtNumber: 5)
        ]
    }
    
    var teams: [Team] {
        [Team(id: 1,
              image: "fc-barcelona",
              name: "Barcelona",
              foreignPlayers: 5,
              nationalTeamPlayers: 8,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 2,
              image: "liverpool-fc",
              name: "Liverpool",
              foreignPlayers: 7,
              nationalTeamPlayers: 9,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 3,
              image: "bayern",
              name: "Bayern",
              foreignPlayers: 3,
              nationalTeamPlayers: 8,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 4,
              image: "fc-barcelona",
              name: "Barcelona",
              foreignPlayers: 8,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 5,
              image: "liverpool-fc",
              name: "Liverpool",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 6,
              image: "bayern",
              name: "Bayern",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 7,
              image: "fc-barcelona",
              name: "Barcelona",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 8,
              image: "liverpool-fc",
              name: "Liverpool",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 9,
              image: "bayern",
              name: "Bayern",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 10,
              image: "fc-barcelona",
              name: "Barcelona",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 11,
              image: "liverpool-fc",
              name: "Liverpool",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 12,
              image: "bayern",
              name: "Bayern",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 13,
              image: "fc-barcelona",
              name: "Barcelona",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 14,
              image: "liverpool-fc",
              name: "Liverpool",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 15,
              image: "bayern",
              name: "Bayern",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 16,
              image: "fc-barcelona",
              name: "Barcelona",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 17,
              image: "liverpool-fc",
              name: "Liverpool",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players),
         Team(id: 18,
              image: "bayern",
              name: "Bayern",
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              wins: 23,
              losses: 15,
              tournaments: ["1. league", "2. league"],
              coachName: "Jose Mourinho",
              foundationDate: "3.4.1899.",
              country: "Croatia",
              players: players)]
    }
}
