//
//  TeamsViewModel.swift
//  SofaScoreAcademy
//
//  Created by Matija Kruljac on 05.03.2021..
//

import Foundation

class TeamsViewModel {
    
    func getTeams() -> [Team] {
        [Team(id: 1,
              name: "Dinamo",
              totalPlayers: 10,
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              tournaments: ["1. league", "2. league"],
              coachName: "Branko Stromar",
              foundationDate: "3.4.1899.",
              country: "Nigdjezemska",
              players: []),
         Team(id: 2,
              name: "Dinamo",
              totalPlayers: 10,
              foreignPlayers: 5,
              nationalTeamPlayers: 5,
              tournaments: ["1. league", "2. league"],
              coachName: "Branko Stromar",
              foundationDate: "3.4.1899.",
              country: "Nigdjezemska",
              players: []),
         Team(id: 3,
               name: "Dinamo",
               totalPlayers: 10,
               foreignPlayers: 5,
               nationalTeamPlayers: 5,
               tournaments: ["1. league", "2. league"],
               coachName: "Branko Stromar",
               foundationDate: "3.4.1899.",
               country: "Nigdjezemska",
               players: []),
          Team(id: 4,
               name: "Dinamo",
               totalPlayers: 10,
               foreignPlayers: 5,
               nationalTeamPlayers: 5,
               tournaments: ["1. league", "2. league"],
               coachName: "Branko Stromar",
               foundationDate: "3.4.1899.",
               country: "Nigdjezemska",
               players: []),
          Team(id: 5,
                name: "Dinamo",
                totalPlayers: 10,
                foreignPlayers: 5,
                nationalTeamPlayers: 5,
                tournaments: ["1. league", "2. league"],
                coachName: "Branko Stromar",
                foundationDate: "3.4.1899.",
                country: "Nigdjezemska",
                players: []),
           Team(id: 6,
                name: "Dinamo",
                totalPlayers: 10,
                foreignPlayers: 5,
                nationalTeamPlayers: 5,
                tournaments: ["1. league", "2. league"],
                coachName: "Branko Stromar",
                foundationDate: "3.4.1899.",
                country: "Nigdjezemska",
                players: []),
           Team(id: 7,
                 name: "Dinamo",
                 totalPlayers: 10,
                 foreignPlayers: 5,
                 nationalTeamPlayers: 5,
                 tournaments: ["1. league", "2. league"],
                 coachName: "Branko Stromar",
                 foundationDate: "3.4.1899.",
                 country: "Nigdjezemska",
                 players: []),
            Team(id: 8,
                 name: "Dinamo",
                 totalPlayers: 10,
                 foreignPlayers: 5,
                 nationalTeamPlayers: 5,
                 tournaments: ["1. league", "2. league"],
                 coachName: "Branko Stromar",
                 foundationDate: "3.4.1899.",
                 country: "Nigdjezemska",
                 players: []),
            Team(id: 9,
                  name: "Dinamo",
                  totalPlayers: 10,
                  foreignPlayers: 5,
                  nationalTeamPlayers: 5,
                  tournaments: ["1. league", "2. league"],
                  coachName: "Branko Stromar",
                  foundationDate: "3.4.1899.",
                  country: "Nigdjezemska",
                  players: []),
             Team(id: 10,
                  name: "Dinamo",
                  totalPlayers: 10,
                  foreignPlayers: 5,
                  nationalTeamPlayers: 5,
                  tournaments: ["1. league", "2. league"],
                  coachName: "Branko Stromar",
                  foundationDate: "3.4.1899.",
                  country: "Nigdjezemska",
                  players: [])]
    }
}
